#!/usr/bin/env bash
# Bring up a Fabric CFT (Raft) network for benchmarking and deploy the kvstore
# chaincode. Wraps the official fabric-samples test-network.
# See docs/decisions/adr-014-fabric-v3-release-pin.md.
#
#   ./up.sh [profile]     profile defaults to $BENCH_PROFILE or "local"
#
# fabric-samples stopped publishing per-version tags after v2.4.9; its test-network
# on the default branch supports Fabric 2.5.x and 3.x. So we pin only the Fabric
# *binary/image* version (FABRIC_VERSION) and take fabric-samples at SAMPLES_REF.
#
# Outputs deploy/docker/fabric-cft/connection.env with the paths + endpoints the
# run config's adapter block needs.
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
need docker; need curl; need jq; need python3
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# On failure: report the failing command and dump the network's containers.
on_error_dump '^(peer|orderer|ca_|dev-peer)'


# --- pinned versions (ADR-014) -------------------------------------------------
FABRIC_VERSION="${FABRIC_VERSION:-2.5.16}"     # LTS 2.5.x, Raft orderer
FABRIC_CA_VERSION="${FABRIC_CA_VERSION:-1.5.22}"
SAMPLES_REF="${SAMPLES_REF:-134c582ac1c105965b3d554874a28fc80ec592f1}"  # fabric-samples main @ 2026-09-08; no per-version tags after v2.4.9

CHANNEL="${CHANNEL:-mychannel}"
CC_NAME="kvstore"
CC_SRC="${REPO_ROOT}/chaincodes/kvstore"

# --- shared fabric-samples checkout + version-matched binaries --------------
SAMPLES="$(fabric_samples_bootstrap "$FABRIC_VERSION" "$FABRIC_CA_VERSION" "$SAMPLES_REF")"
export PATH="${SAMPLES}/bin:${PATH}"
export FABRIC_CFG_PATH="${SAMPLES}/config"

# --- pin orderer batch params from the resource profile (ADR-011) -----------
patch_orderer_batch fabric-cft "${SAMPLES}/test-network/configtx/configtx.yaml"

# --- start the network (Raft orderer, LevelDB, TLS, CA) ---------------------
# Orderer batch params were already patched into configtx.yaml above; the
# network.sh `-o` flag selects the orderer type (etcdraft|BFT), not batch config.
cd "${SAMPLES}/test-network" || exit 1
./network.sh down || true
drop_caches
./network.sh up createChannel -c "$CHANNEL" -s leveldb \
  || die "fabric-cft: network.sh up createChannel failed" "its output is above; containers are dumped below"
log "deploying ${CC_NAME} chaincode from ${CC_SRC}"
./network.sh deployCC -c "$CHANNEL" -ccn "$CC_NAME" -ccp "$CC_SRC" -ccl go -ccv 1.0 -ccs 1 \
  || die "fabric-cft: chaincode deploy failed" "Go build errors in chaincodes/kvstore show above; 'docker logs peer0.org1.example.com' has lifecycle errors"

# --- resource budget (equal total across platforms, split evenly) ------------
warm_chaincode "${SAMPLES}/test-network" "$CHANNEL" "$CC_NAME" 1 2
RES_ENV="$(apply_budget fabric-cft '^(peer0\.org[12]\.example\.com|orderer\.example\.com|dev-peer)')"

# --- emit connection.env for the run config --------------------------------
ORG1="${SAMPLES}/test-network/organizations/peerOrganizations/org1.example.com"
USER_MSP="${ORG1}/users/User1@org1.example.com/msp"
CERT="$(user_signcert "$USER_MSP")"
check_paths "$CERT" "${USER_MSP}/keystore" "${ORG1}/peers/peer0.org1.example.com/tls/ca.crt"
cat > "${HERE}/connection.env" <<EOF
# generated by deploy/docker/fabric-cft/up.sh  ($(date -u +%FT%TZ))
# generic BENCH_ADAPTER_* names so one run config works for fabric-cft/-bft/drunix
BENCH_ADAPTER_PEER_ENDPOINT=localhost:7051
BENCH_ADAPTER_ENDORSE_ENDPOINT=localhost:7051
BENCH_ADAPTER_COMMIT_ENDPOINT=localhost:7051
BENCH_ADAPTER_GATEWAY_PEER=peer0.org1.example.com
BENCH_ADAPTER_MSP_ID=Org1MSP
BENCH_ADAPTER_CERT_PATH=${CERT}
BENCH_ADAPTER_KEY_PATH=${USER_MSP}/keystore
BENCH_ADAPTER_TLS_CA_CERT_PATH=${ORG1}/peers/peer0.org1.example.com/tls/ca.crt
BENCH_ADAPTER_CHANNEL=${CHANNEL}
BENCH_ADAPTER_CHAINCODE=${CC_NAME}
BENCH_ADAPTER_METRICS_ENDPOINT=http://localhost:9443/metrics
BENCH_PLATFORM_VERSION=${FABRIC_VERSION}
# State DB this network actually came up on; the harness records it as
# manifest.state_db next to the requested value (fairness lever).
BENCH_ACTUAL_STATE_DB=leveldb
${RES_ENV}
EOF
log "wrote ${HERE}/connection.env"
log "fabric-cft up. peer :7051  orderer :7050  operations :9443"
