#!/usr/bin/env bash
# Bring up a Fabric CFT (Raft) network for benchmarking and deploy the kvstore
# chaincode. Wraps the official fabric-samples test-network.
# See docs/decisions/adr-014-fabric-v3-release-pin.md.
#
#   ./up.sh [profile]     profile defaults to $BENCH_PROFILE or "local"
#
# fabric-samples stopped publishing per-version tags after v2.4.9; its test-network
# on the default branch supports Fabric 2.5.x and 3.x. So we pin only the Fabric
# *binary/image* version (FABRIC_VERSION) and take fabric-samples at SAMPLES_REF.
#
# Outputs deploy/docker/fabric-cft/connection.env with the paths + endpoints the
# run config's adapter block needs.
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
need docker; need curl; need jq
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- pinned versions (ADR-014) -------------------------------------------------
FABRIC_VERSION="${FABRIC_VERSION:-2.5.16}"     # LTS 2.5.x, Raft orderer
FABRIC_CA_VERSION="${FABRIC_CA_VERSION:-1.5.22}"
SAMPLES_REF="${SAMPLES_REF:-main}"             # no per-version tags after v2.4.9
CACHE="${HERE}/.cache"
SAMPLES="${CACHE}/fabric-samples"

CHANNEL="${CHANNEL:-mychannel}"
CC_NAME="kvstore"
CC_SRC="${REPO_ROOT}/chaincodes/kvstore"

# --- fetch fabric-samples + binaries + images at the pinned version ----------
mkdir -p "$CACHE"
if [ ! -d "$SAMPLES/.git" ]; then
  log "cloning fabric-samples @ ${SAMPLES_REF}"
  git clone --depth 1 --branch "$SAMPLES_REF" https://github.com/hyperledger/fabric-samples.git "$SAMPLES"
fi
if [ ! -x "${SAMPLES}/bin/peer" ] || [ ! -f "${SAMPLES}/config/core.yaml" ]; then
  log "installing Fabric ${FABRIC_VERSION} binaries + config + docker images"
  ( cd "$SAMPLES" && curl -sSL https://raw.githubusercontent.com/hyperledger/fabric/main/scripts/install-fabric.sh \
      | bash -s -- --fabric-version "$FABRIC_VERSION" --ca-version "$FABRIC_CA_VERSION" binary docker )
fi
[ -f "${SAMPLES}/config/core.yaml" ] || die "install-fabric did not produce ${SAMPLES}/config/core.yaml"
export PATH="${SAMPLES}/bin:${PATH}"
export FABRIC_CFG_PATH="${SAMPLES}/config"

# --- pin orderer batch params from the resource profile (ADR-011) -----------
CONFIGTX="${SAMPLES}/test-network/configtx/configtx.yaml"
if [ -f "$CONFIGTX" ]; then
  BT="$(platform_field fabric-cft orderer_batch.batch_timeout       || echo 1s)"
  MMC="$(platform_field fabric-cft orderer_batch.max_message_count   || echo 100)"
  PMB="$(platform_field fabric-cft orderer_batch.preferred_max_bytes || echo '2 MB')"
  AMB="$(platform_field fabric-cft orderer_batch.absolute_max_bytes  || echo '10 MB')"
  log "pinning orderer batch: timeout=${BT} maxMsgCount=${MMC} preferred=${PMB} absolute=${AMB}"
  python3 - "$CONFIGTX" "$BT" "$MMC" "$PMB" "$AMB" <<'PY'
import re, sys
path, bt, mmc, pmb, amb = sys.argv[1:6]
s = open(path).read()
s = re.sub(r'BatchTimeout:\s*\S+',           f'BatchTimeout: {bt}', s, count=1)
s = re.sub(r'MaxMessageCount:\s*\d+',         f'MaxMessageCount: {mmc}', s, count=1)
s = re.sub(r'PreferredMaxBytes:\s*[^\n]+',    f'PreferredMaxBytes: {pmb}', s, count=1)
s = re.sub(r'AbsoluteMaxBytes:\s*[^\n]+',     f'AbsoluteMaxBytes: {amb}', s, count=1)
open(path, 'w').write(s)
PY
fi

# --- start the network (Raft orderer, LevelDB, TLS, CA) ---------------------
# Orderer batch params were already patched into configtx.yaml above; the
# network.sh `-o` flag selects the orderer type (etcdraft|BFT), not batch config.
cd "${SAMPLES}/test-network"
./network.sh down || true
drop_caches
./network.sh up createChannel -c "$CHANNEL" -s leveldb
log "deploying ${CC_NAME} chaincode from ${CC_SRC}"
./network.sh deployCC -c "$CHANNEL" -ccn "$CC_NAME" -ccp "$CC_SRC" -ccl go -ccv 1.0 -ccs 1

# --- emit connection.env for the run config --------------------------------
ORG1="${SAMPLES}/test-network/organizations/peerOrganizations/org1.example.com"
USER_MSP="${ORG1}/users/User1@org1.example.com/msp"
CERT="$(ls "${USER_MSP}"/signcerts/* 2>/dev/null | head -1)"
KEY="$(ls "${USER_MSP}"/keystore/* 2>/dev/null | head -1)"
cat > "${HERE}/connection.env" <<EOF
# generated by deploy/docker/fabric-cft/up.sh  ($(date -u +%FT%TZ))
# generic BENCH_ADAPTER_* names so one run config works for fabric-cft/-bft/drunix
BENCH_ADAPTER_PEER_ENDPOINT=localhost:7051
BENCH_ADAPTER_ENDORSE_ENDPOINT=localhost:7051
BENCH_ADAPTER_COMMIT_ENDPOINT=localhost:7051
BENCH_ADAPTER_GATEWAY_PEER=peer0.org1.example.com
BENCH_ADAPTER_MSP_ID=Org1MSP
BENCH_ADAPTER_CERT_PATH=${CERT:-${USER_MSP}/signcerts/User1@org1.example.com-cert.pem}
BENCH_ADAPTER_KEY_PATH=${USER_MSP}/keystore
BENCH_ADAPTER_TLS_CA_CERT_PATH=${ORG1}/peers/peer0.org1.example.com/tls/ca.crt
BENCH_ADAPTER_CHANNEL=${CHANNEL}
BENCH_ADAPTER_CHAINCODE=${CC_NAME}
BENCH_ADAPTER_METRICS_ENDPOINT=http://localhost:9443/metrics
BENCH_PLATFORM_VERSION=${FABRIC_VERSION}
EOF
log "wrote ${HERE}/connection.env"
log "fabric-cft up. peer :7051  orderer :7050  operations :9443"
