#!/usr/bin/env bash
# Bring up Fabric-X for benchmarking: the fabric-x-samples "tokens" stack
# (devnet Arma+committer + issuer/endorser/owner services) plus the custom
# kv-write view service. Emits connection.env for the fabricx adapter.
#
#   ./up.sh [profile]
#
# Verified against hyperledger/fabric-x-samples @ main:
#   tokens/  `make setup && make start`  ->  devnet + token services
#   ports: issuer :9100  endorser1 :9300  owner1 :9500  owner2 :9600
#   custom kvview: :9700
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
need docker; need git; need make; need go
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

FXS_REF="${FXS_REF:-main}"
CACHE="${HERE}/.cache"
FXS="${CACHE}/fabric-x-samples"
mkdir -p "$CACHE"

[ -d "$FXS/.git" ] || git clone --depth 1 -b "$FXS_REF" \
  https://github.com/hyperledger/fabric-x-samples.git "$FXS"

echo "== fabric-x-samples tokens: make setup && make start (slow: builds images) =="
( cd "$FXS/tokens" && make setup && make start )

echo "== initialise the token network (endorser init) =="
curl -sf -X POST http://localhost:9300/endorser/init || warn "endorser init returned non-zero (may already be initialised)"

echo "== build + start the custom kv-write view service =="
docker build -t bench/fabricx-rest:latest "$HERE/kvview"
export FXS_DEVNET_CONF="$FXS/devnet/config"
drop_caches
docker compose up -d

# quick liveness
curl -sf http://localhost:9700/healthz >/dev/null && log "kvview :9700 healthy" \
  || warn "kvview :9700 not healthy yet"

cat > "${HERE}/connection.env" <<EOF
# generated by deploy/docker/fabricx/up.sh  ($(date -u +%FT%TZ))
BENCH_ADAPTER_OWNER_URL=http://localhost:9500
BENCH_ADAPTER_ISSUER_URL=http://localhost:9100
BENCH_ADAPTER_KV_URL=http://localhost:9700
BENCH_ADAPTER_SENDER_ACCOUNT=alice
BENCH_ADAPTER_COUNTERPARTY_NODE=owner2
BENCH_ADAPTER_TOKEN_CODE=EURX
BENCH_ADAPTER_METRICS_ENDPOINT=http://localhost:9301/metrics
BENCH_PLATFORM_VERSION=fabric-x-samples-${FXS_REF}
EOF
log "fabricx up. token API :9100/:9500  kv-write view :9700"
warn "kv-write view is a Phase-3 stub (POST /kv -> 501); see deploy/docker/fabricx/kvview/README.md"
