#!/usr/bin/env bash
# Fabric-X deploy - PHASE 3 (scaffold). Clones the upstream repos at pinned tags,
# prefers their own sample compose if present, otherwise brings up the reference
# scaffold in docker-compose.yml. Emits connection.env for the fabricx adapter.
#
#   ./up.sh [profile]
#
# Ports / images / config in docker-compose.yml are PLACEHOLDERS - align with
# hyperledger/fabric-x + hyperledger/fabric-x-orderer during Phase 3.
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
need docker; need git
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

FX_REF="${FX_REF:-main}"
FXO_REF="${FXO_REF:-main}"
CACHE="${HERE}/.cache"
mkdir -p "$CACHE"

[ -d "$CACHE/fabric-x/.git" ]         || git clone --depth 1 -b "$FX_REF"  https://github.com/hyperledger/fabric-x.git         "$CACHE/fabric-x"
[ -d "$CACHE/fabric-x-orderer/.git" ] || git clone --depth 1 -b "$FXO_REF" https://github.com/hyperledger/fabric-x-orderer.git "$CACHE/fabric-x-orderer"

BENCH_FX_CPUS="$(platform_field fabricx per_container.cpus   || echo 0.8)"
BENCH_FX_MEM="$(platform_field fabricx per_container.memory   || echo 800m)"
export BENCH_FX_CPUS BENCH_FX_MEM

# Prefer an upstream sample compose if one exists.
UPSTREAM_COMPOSE="$(find "$CACHE/fabric-x" "$CACHE/fabric-x-orderer" -maxdepth 4 \
  \( -name 'docker-compose*.y*ml' -o -name 'compose*.y*ml' \) 2>/dev/null | head -1 || true)"

drop_caches
if [ -n "$UPSTREAM_COMPOSE" ]; then
  warn "using upstream sample compose: $UPSTREAM_COMPOSE"
  warn "review it against deploy/profiles resource limits before a real run"
  docker compose -f "$UPSTREAM_COMPOSE" up -d
else
  warn "no upstream sample compose found - bringing up the reference scaffold"
  warn "images/ports/config are PLACEHOLDERS; a working network needs Phase 3 completion"
  docker compose up -d || true
fi

cat > "${HERE}/connection.env" <<EOF
# generated by deploy/docker/fabricx/up.sh  ($(date -u +%FT%TZ))
BENCH_ADAPTER_BASE_URL=http://localhost:8080
BENCH_ADAPTER_FINALITY_MODE=poll
BENCH_ADAPTER_METRICS_ENDPOINT=http://localhost:9643/metrics
BENCH_PLATFORM_VERSION=fabricx-${FX_REF}
EOF
log "fabricx scaffold up. REST façade (adapter target) :8080  committer /metrics :9643"
