#!/usr/bin/env bash
# Bring up a Fabric BFT (SmartBFT) network for benchmarking and deploy kvstore.
# Wraps fabric-samples test-network pinned to a v3.1.x tag; SmartBFT requires
# 3f+1 orderers (minimum 4). See docs/decisions/adr-014-fabric-v3-release-pin.md.
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
need docker; need curl; need jq
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

FABRIC_VERSION="${FABRIC_VERSION:-3.1.5}"
FABRIC_CA_VERSION="${FABRIC_CA_VERSION:-1.5.22}"
SAMPLES_REF="${SAMPLES_REF:-main}"
CACHE="${HERE}/.cache"
SAMPLES="${CACHE}/fabric-samples"
CHANNEL="${CHANNEL:-mychannel}"
CC_NAME="kvstore"
CC_SRC="${REPO_ROOT}/chaincodes/kvstore"

mkdir -p "$CACHE"
if [ ! -d "$SAMPLES/.git" ]; then
  log "cloning fabric-samples @ ${SAMPLES_REF}"
  git clone --depth 1 --branch "$SAMPLES_REF" https://github.com/hyperledger/fabric-samples.git "$SAMPLES"
fi
if [ ! -x "${SAMPLES}/bin/peer" ] || [ ! -f "${SAMPLES}/config/core.yaml" ]; then
  log "installing Fabric ${FABRIC_VERSION} binaries + config + docker images"
  ( cd "$SAMPLES" && curl -sSL https://raw.githubusercontent.com/hyperledger/fabric/main/scripts/install-fabric.sh \
      | bash -s -- --fabric-version "$FABRIC_VERSION" --ca-version "$FABRIC_CA_VERSION" binary docker )
fi
[ -f "${SAMPLES}/config/core.yaml" ] || die "install-fabric did not produce ${SAMPLES}/config/core.yaml"
export PATH="${SAMPLES}/bin:${PATH}"
export FABRIC_CFG_PATH="${SAMPLES}/config"

CONFIGTX="${SAMPLES}/test-network/configtx/configtx.yaml"
if [ -f "$CONFIGTX" ]; then
  BT="$(platform_field fabric-bft orderer_batch.batch_timeout       || echo 1s)"
  MMC="$(platform_field fabric-bft orderer_batch.max_message_count   || echo 100)"
  PMB="$(platform_field fabric-bft orderer_batch.preferred_max_bytes || echo '2 MB')"
  AMB="$(platform_field fabric-bft orderer_batch.absolute_max_bytes  || echo '10 MB')"
  log "pinning orderer batch: timeout=${BT} maxMsgCount=${MMC} preferred=${PMB} absolute=${AMB}"
  python3 - "$CONFIGTX" "$BT" "$MMC" "$PMB" "$AMB" <<'PY'
import re, sys
path, bt, mmc, pmb, amb = sys.argv[1:6]
s = open(path).read()
s = re.sub(r'BatchTimeout:\s*\S+',        f'BatchTimeout: {bt}', s, count=1)
s = re.sub(r'MaxMessageCount:\s*\d+',     f'MaxMessageCount: {mmc}', s, count=1)
s = re.sub(r'PreferredMaxBytes:\s*[^\n]+',f'PreferredMaxBytes: {pmb}', s, count=1)
s = re.sub(r'AbsoluteMaxBytes:\s*[^\n]+', f'AbsoluteMaxBytes: {amb}', s, count=1)
open(path,'w').write(s)
PY
fi

cd "${SAMPLES}/test-network"
./network.sh down || true
drop_caches
# -bft selects the SmartBFT ordering service (4 orderers).
./network.sh up createChannel -c "$CHANNEL" -s leveldb -bft
./network.sh deployCC -c "$CHANNEL" -ccn "$CC_NAME" -ccp "$CC_SRC" -ccl go -ccv 1 -ccs 1

ORG1="${SAMPLES}/test-network/organizations/peerOrganizations/org1.example.com"
cat > "${HERE}/connection.env" <<EOF
# generated by deploy/docker/fabric-bft/up.sh  ($(date -u +%FT%TZ))
BENCH_ADAPTER_PEER_ENDPOINT=localhost:7051
BENCH_ADAPTER_ENDORSE_ENDPOINT=localhost:7051
BENCH_ADAPTER_COMMIT_ENDPOINT=localhost:7051
BENCH_ADAPTER_GATEWAY_PEER=peer0.org1.example.com
BENCH_ADAPTER_MSP_ID=Org1MSP
BENCH_ADAPTER_CERT_PATH=${ORG1}/users/User1@org1.example.com/msp/signcerts/cert.pem
BENCH_ADAPTER_KEY_PATH=${ORG1}/users/User1@org1.example.com/msp/keystore
BENCH_ADAPTER_TLS_CA_CERT_PATH=${ORG1}/peers/peer0.org1.example.com/tls/ca.crt
BENCH_ADAPTER_CHANNEL=${CHANNEL}
BENCH_ADAPTER_CHAINCODE=${CC_NAME}
BENCH_ADAPTER_METRICS_ENDPOINT=http://localhost:9443/metrics
BENCH_PLATFORM_VERSION=${FABRIC_VERSION}
EOF
log "fabric-bft up (SmartBFT, 4 orderers). peer :7051  operations :9443"
