#!/usr/bin/env bash
# Bring up a Fabric BFT (SmartBFT) network for benchmarking and deploy kvstore.
# Wraps fabric-samples test-network pinned to a v3.1.x tag; SmartBFT requires
# 3f+1 orderers (minimum 4). See docs/decisions/adr-014-fabric-v3-release-pin.md.
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
need docker; need curl; need jq; need python3
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
on_error_dump '^(peer|orderer|ca_|dev-peer)'


FABRIC_VERSION="${FABRIC_VERSION:-3.1.5}"
FABRIC_CA_VERSION="${FABRIC_CA_VERSION:-1.5.22}"
SAMPLES_REF="${SAMPLES_REF:-134c582ac1c105965b3d554874a28fc80ec592f1}"  # fabric-samples main @ 2026-09-08; no per-version tags after v2.4.9
CHANNEL="${CHANNEL:-mychannel}"
CC_NAME="kvstore"
CC_SRC="${REPO_ROOT}/chaincodes/kvstore"

SAMPLES="$(fabric_samples_bootstrap "$FABRIC_VERSION" "$FABRIC_CA_VERSION" "$SAMPLES_REF")"
export PATH="${SAMPLES}/bin:${PATH}"
export FABRIC_CFG_PATH="${SAMPLES}/config"

# BFT uses test-network/bft-config/configtx.yaml (SmartBFT profile). Patch it -
# NOT the Raft configtx/configtx.yaml. SmartBFT ALSO has request-level batching
# (RequestBatchMaxCount / RequestBatchMaxInterval) that CFT lacks; align those to
# the same block-cut params so BFT does not batch far tighter than CFT. The
# remaining SmartBFT-vs-Raft batching differences are inherent and disclosed
# (docs/decisions/adr-011-orderer-batch-params.md).
BFT_CONFIGTX="${SAMPLES}/test-network/bft-config/configtx.yaml"
[ -f "$BFT_CONFIGTX" ] || die "fabric-bft: ${BFT_CONFIGTX} missing - the pinned fabric-samples has no SmartBFT config"
patch_orderer_batch fabric-bft "$BFT_CONFIGTX" bft
if [ -f "${SAMPLES}/test-network/configtx/configtx.yaml" ]; then
  patch_orderer_batch fabric-bft "${SAMPLES}/test-network/configtx/configtx.yaml" bft
fi

cd "${SAMPLES}/test-network" || exit 1
./network.sh down || true
drop_caches
# -bft selects the SmartBFT ordering service (4 orderers).
./network.sh up createChannel -c "$CHANNEL" -s leveldb -bft \
  || die "fabric-bft: network.sh up createChannel -bft failed" "its output is above; containers are dumped below"
./network.sh deployCC -c "$CHANNEL" -ccn "$CC_NAME" -ccp "$CC_SRC" -ccl go -ccv 1.0 -ccs 1 \
  || die "fabric-bft: chaincode deploy failed" "'docker logs peer0.org1.example.com' has lifecycle errors"

# --- resource budget (equal total across platforms, split evenly) ------------
warm_chaincode "${SAMPLES}/test-network" "$CHANNEL" "$CC_NAME" 1 2
RES_ENV="$(apply_budget fabric-bft '^(peer0\.org[12]\.example\.com|orderer[0-9]*\.example\.com|dev-peer)')"

ORG1="${SAMPLES}/test-network/organizations/peerOrganizations/org1.example.com"
USER_MSP="${ORG1}/users/User1@org1.example.com/msp"
CERT="$(user_signcert "$USER_MSP")"
check_paths "$CERT" "${USER_MSP}/keystore" "${ORG1}/peers/peer0.org1.example.com/tls/ca.crt"
cat > "${HERE}/connection.env" <<EOF
# generated by deploy/docker/fabric-bft/up.sh  ($(date -u +%FT%TZ))
BENCH_ADAPTER_PEER_ENDPOINT=localhost:7051
BENCH_ADAPTER_ENDORSE_ENDPOINT=localhost:7051
BENCH_ADAPTER_COMMIT_ENDPOINT=localhost:7051
BENCH_ADAPTER_GATEWAY_PEER=peer0.org1.example.com
BENCH_ADAPTER_MSP_ID=Org1MSP
BENCH_ADAPTER_CERT_PATH=${CERT}
BENCH_ADAPTER_KEY_PATH=${USER_MSP}/keystore
BENCH_ADAPTER_TLS_CA_CERT_PATH=${ORG1}/peers/peer0.org1.example.com/tls/ca.crt
BENCH_ADAPTER_CHANNEL=${CHANNEL}
BENCH_ADAPTER_CHAINCODE=${CC_NAME}
BENCH_ADAPTER_METRICS_ENDPOINT=http://localhost:9443/metrics
BENCH_PLATFORM_VERSION=${FABRIC_VERSION}
# State DB this network actually came up on; the harness records it as
# manifest.state_db next to the requested value (fairness lever).
BENCH_ACTUAL_STATE_DB=leveldb
${RES_ENV}
EOF
log "fabric-bft up (SmartBFT, 4 orderers). peer :7051  operations :9443"
