#!/usr/bin/env bash
# Bring up a Fabric BFT (SmartBFT) network for benchmarking and deploy kvstore.
# Wraps fabric-samples test-network pinned to a v3.1.x tag; SmartBFT requires
# 3f+1 orderers (minimum 4). See docs/decisions/adr-014-fabric-v3-release-pin.md.
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
need docker; need curl; need jq
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

FABRIC_VERSION="${FABRIC_VERSION:-3.1.5}"
FABRIC_CA_VERSION="${FABRIC_CA_VERSION:-1.5.22}"
SAMPLES_REF="${SAMPLES_REF:-main}"
CHANNEL="${CHANNEL:-mychannel}"
CC_NAME="kvstore"
CC_SRC="${REPO_ROOT}/chaincodes/kvstore"

SAMPLES="$(fabric_samples_bootstrap "$FABRIC_VERSION" "$FABRIC_CA_VERSION" "$SAMPLES_REF")"
export PATH="${SAMPLES}/bin:${PATH}"
export FABRIC_CFG_PATH="${SAMPLES}/config"

# BFT uses test-network/bft-config/configtx.yaml (SmartBFT profile). Patch it -
# NOT the Raft configtx/configtx.yaml. SmartBFT ALSO has request-level batching
# (RequestBatchMaxCount / RequestBatchMaxInterval) that CFT lacks; align those to
# the same block-cut params so BFT does not batch far tighter than CFT. The
# remaining SmartBFT-vs-Raft batching differences are inherent and disclosed
# (docs/decisions/adr-011-orderer-batch-params.md).
BT="$(platform_field fabric-bft orderer_batch.batch_timeout       || echo 1s)"
MMC="$(platform_field fabric-bft orderer_batch.max_message_count   || echo 100)"
PMB="$(platform_field fabric-bft orderer_batch.preferred_max_bytes || echo '2 MB')"
AMB="$(platform_field fabric-bft orderer_batch.absolute_max_bytes  || echo '10 MB')"
for CONFIGTX in "${SAMPLES}/test-network/bft-config/configtx.yaml" "${SAMPLES}/test-network/configtx/configtx.yaml"; do
  [ -f "$CONFIGTX" ] || continue
  log "pinning orderer batch in ${CONFIGTX##*/}: timeout=${BT} maxMsgCount=${MMC} preferred=${PMB} absolute=${AMB}"
  python3 - "$CONFIGTX" "$BT" "$MMC" "$PMB" "$AMB" <<'PY'
import re, sys
path, bt, mmc, pmb, amb = sys.argv[1:6]
s = open(path).read()
s = re.sub(r'BatchTimeout:\s*\S+',            f'BatchTimeout: {bt}', s, count=1)
s = re.sub(r'MaxMessageCount:\s*\d+',         f'MaxMessageCount: {mmc}', s, count=1)
s = re.sub(r'PreferredMaxBytes:\s*[^\n]+',    f'PreferredMaxBytes: {pmb}', s, count=1)
s = re.sub(r'AbsoluteMaxBytes:\s*[^\n]+',     f'AbsoluteMaxBytes: {amb}', s, count=1)
# SmartBFT request batching -> match the block-cut count so BFT doesn't cut tighter
s = re.sub(r'RequestBatchMaxCount:\s*\d+',    f'RequestBatchMaxCount: {mmc}', s)
s = re.sub(r'RequestBatchMaxInterval:\s*\S+', f'RequestBatchMaxInterval: {bt}', s)
open(path,'w').write(s)
PY
done

cd "${SAMPLES}/test-network"
./network.sh down || true
drop_caches
# -bft selects the SmartBFT ordering service (4 orderers).
./network.sh up createChannel -c "$CHANNEL" -s leveldb -bft
./network.sh deployCC -c "$CHANNEL" -ccn "$CC_NAME" -ccp "$CC_SRC" -ccl go -ccv 1.0 -ccs 1

# --- resource budget (equal total across platforms, split evenly) ------------
warm_chaincode "${SAMPLES}/test-network" "$CHANNEL" "$CC_NAME" 1 2
RES_ENV="$(apply_budget fabric-bft '^(peer0\.org[12]\.example\.com|orderer[0-9]*\.example\.com|dev-peer)')"

ORG1="${SAMPLES}/test-network/organizations/peerOrganizations/org1.example.com"
USER_MSP="${ORG1}/users/User1@org1.example.com/msp"
CERT="$(ls "${USER_MSP}"/signcerts/* 2>/dev/null | head -1)"
cat > "${HERE}/connection.env" <<EOF
# generated by deploy/docker/fabric-bft/up.sh  ($(date -u +%FT%TZ))
BENCH_ADAPTER_PEER_ENDPOINT=localhost:7051
BENCH_ADAPTER_ENDORSE_ENDPOINT=localhost:7051
BENCH_ADAPTER_COMMIT_ENDPOINT=localhost:7051
BENCH_ADAPTER_GATEWAY_PEER=peer0.org1.example.com
BENCH_ADAPTER_MSP_ID=Org1MSP
BENCH_ADAPTER_CERT_PATH=${CERT:-${USER_MSP}/signcerts/User1@org1.example.com-cert.pem}
BENCH_ADAPTER_KEY_PATH=${USER_MSP}/keystore
BENCH_ADAPTER_TLS_CA_CERT_PATH=${ORG1}/peers/peer0.org1.example.com/tls/ca.crt
BENCH_ADAPTER_CHANNEL=${CHANNEL}
BENCH_ADAPTER_CHAINCODE=${CC_NAME}
BENCH_ADAPTER_METRICS_ENDPOINT=http://localhost:9443/metrics
BENCH_PLATFORM_VERSION=${FABRIC_VERSION}
# State DB this network actually came up on; the harness records it as
# manifest.state_db next to the requested value (fairness lever).
BENCH_ACTUAL_STATE_DB=leveldb
${RES_ENV}
EOF
log "fabric-bft up (SmartBFT, 4 orderers). peer :7051  operations :9443"
