#!/usr/bin/env bash
# Bring up a Drunix network (Lite Peer + Committing Peer + Validation Service +
# Raft orderer + KeyDB) and deploy the kvstore chaincode.
#
# Drunix is HLF 2.5.x-compatible, so this wraps drunix-network/test-network from
# the NPCI Drunix repo the same way fabric-cft wraps fabric-samples. Normalized
# runs use LevelDB; YugabyteDB is only wired in for platform-native runs.
#
# NOTE: set BENCH_DRUNIX_REPO to a local checkout or a clone URL of the Drunix
# source. The repo layout is expected to expose drunix-network/test-network/
# with a network.sh compatible with the fabric-samples one.
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
need docker; need git
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DRUNIX_REPO="${BENCH_DRUNIX_REPO:-}"
DRUNIX_REF="${BENCH_DRUNIX_REF:-main}"
CACHE="${HERE}/.cache"
SRC="${CACHE}/drunix"
CHANNEL="${CHANNEL:-mychannel}"
CC_NAME="kvstore"
CC_SRC="${REPO_ROOT}/chaincodes/kvstore"

[ -n "$DRUNIX_REPO" ] || die "set BENCH_DRUNIX_REPO to a Drunix git URL or local path (see docs/platforms/drunix.md)"

mkdir -p "$CACHE"
if [ -d "$DRUNIX_REPO/.git" ] || [ -d "$DRUNIX_REPO/drunix-network" ]; then
  SRC="$DRUNIX_REPO"                       # local checkout supplied directly
elif [ ! -d "$SRC/.git" ]; then
  log "cloning Drunix @ ${DRUNIX_REF}"
  git clone --depth 1 --branch "$DRUNIX_REF" "$DRUNIX_REPO" "$SRC"
fi

NET="${SRC}/drunix-network/test-network"
[ -d "$NET" ] || die "expected ${NET} - check the Drunix repo layout"
cd "$NET"

STATE_DB="$(state_db drunix)"
log "drunix state_db=${STATE_DB} (normalized runs must be leveldb)"

./network.sh down || true
drop_caches
# Flags mirror fabric-samples; Drunix adds LP/CP split automatically. If the
# Drunix network.sh uses different flag names, adjust here.
./network.sh up createChannel -c "$CHANNEL" -s "$STATE_DB"
./network.sh deployCC -c "$CHANNEL" -ccn "$CC_NAME" -ccp "$CC_SRC" -ccl go -ccv 1 -ccs 1

ORG1="${NET}/organizations/peerOrganizations/org1.example.com"
cat > "${HERE}/connection.env" <<EOF
# generated by deploy/docker/drunix/up.sh  ($(date -u +%FT%TZ))
# endorse against the Lite Peer; the LP gateway federates commit-status from the CP.
BENCH_ADAPTER_PEER_ENDPOINT=localhost:7051
BENCH_ADAPTER_ENDORSE_ENDPOINT=localhost:7051
BENCH_ADAPTER_COMMIT_ENDPOINT=localhost:7061
BENCH_ADAPTER_GATEWAY_PEER=peer0.org1.example.com
BENCH_ADAPTER_MSP_ID=Org1MSP
BENCH_ADAPTER_CERT_PATH=${ORG1}/users/User1@org1.example.com/msp/signcerts/cert.pem
BENCH_ADAPTER_KEY_PATH=${ORG1}/users/User1@org1.example.com/msp/keystore
BENCH_ADAPTER_TLS_CA_CERT_PATH=${ORG1}/peers/peer0.org1.example.com/tls/ca.crt
BENCH_ADAPTER_CHANNEL=${CHANNEL}
BENCH_ADAPTER_CHAINCODE=${CC_NAME}
BENCH_ADAPTER_METRICS_ENDPOINT=http://localhost:9543/metrics
BENCH_PLATFORM_VERSION=drunix
EOF
log "drunix up. lite-peer :7051  committing-peer :7061"
