init_crypto: true
reset_epoch: true
local_server_ip: 172.30.7.10
server_ips:
  - 172.30.7.10
  - 172.30.7.11
  - 172.30.7.12
  - 172.30.7.13
epoch_ips:
  - 172.30.7.10
  - 172.30.7.11
  - 172.30.7.12
  - 172.30.7.13
cc_type: ycsb
cc_test_func_name: time
send_to_all_client_proxy: true
tr_manager_show_categorize_detail: false
tr_manager_reuse_abort_transaction: false
early_execution: false
early_return: true
async_block_gen: true
aggregation:
  enable: false
  policy: 0
  cluster_ips:
    - 172.30.7.10
    - 172.30.7.11
heart_beat_config:
  table_name: heart_beat_table
  func_name: empty
  reads: 0
  writes: 0
server_data:
  172.30.7.10:
    public_crt: crypto/server.0.public.key
    private_crt: crypto/server.0.private.key
    user_public_crt: crypto/server.0.public.user.key
    user_private_crt: crypto/server.0.private.user.key
  172.30.7.11:
    public_crt: crypto/server.1.public.key
    private_crt: crypto/server.1.private.key
    user_public_crt: crypto/server.1.public.user.key
    user_private_crt: crypto/server.1.private.user.key
  172.30.7.12:
    public_crt: crypto/server.2.public.key
    private_crt: crypto/server.2.private.key
    user_public_crt: crypto/server.2.public.user.key
    user_private_crt: crypto/server.2.private.user.key
  172.30.7.13:
    public_crt: crypto/server.3.public.key
    private_crt: crypto/server.3.private.key
    user_public_crt: crypto/server.3.public.user.key
    user_private_crt: crypto/server.3.private.user.key
epoch_data:
  public_crt: crypto/epoch.public.key
  private_crt: crypto/epoch.private.key
