#!/usr/bin/env bash
# NeuChain deploy - PHASE 4 (partial: build + topology scaffolding in place, the
# adapter and the exact run flags are still TODO - see
# docs/platforms/neuchain-client-implementation.md).
#
#   ./up.sh [profile]
#
# Steps:
#   1. build bench/neuchain-build:ev (Ubuntu 20.04 toolchain) if absent
#   2. build bench/neuchain:ev runtime image if absent
#   3. bring up 4 block servers + 1 epoch server with profile resource limits
#   4. emit connection.env
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
need docker
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

NEUCHAIN_REF="${NEUCHAIN_REF:-ev}"

if ! docker image inspect bench/neuchain-build:ev >/dev/null 2>&1; then
  log "building bench/neuchain-build:ev (this is slow - grpc + NeuChain from source)"
  docker build -f Dockerfile.build --build-arg NEUCHAIN_REF="$NEUCHAIN_REF" \
    -t bench/neuchain-build:ev .
fi
if ! docker image inspect bench/neuchain:ev >/dev/null 2>&1; then
  log "building bench/neuchain:ev runtime image"
  docker build -f Dockerfile.run -t bench/neuchain:ev .
fi

# Resource limits from the profile.
BENCH_NC_CPUS="$(platform_field neuchain per_container.cpus   || echo 1.2)"
BENCH_NC_MEM="$(platform_field neuchain per_container.memory   || echo 1g)"
export BENCH_NC_CPUS BENCH_NC_MEM

warn "NeuChain run flags / config files in docker-compose.yml are PLACEHOLDERS."
warn "Fill them in from the iDC-NEU/NeuChain@ev repo before expecting a working network."

drop_caches
docker compose up -d

cat > "${HERE}/connection.env" <<EOF
# generated by deploy/docker/neuchain/up.sh  ($(date -u +%FT%TZ))
# gRPC submit endpoints - PLACEHOLDER ports, see docker-compose.yml
BENCH_ADAPTER_NEUCHAIN_ENDPOINTS=localhost:19000,localhost:19001,localhost:19002,localhost:19003
BENCH_ADAPTER_NEUCHAIN_EPOCH_ENDPOINT=localhost:18000
BENCH_PLATFORM_VERSION=neuchain-${NEUCHAIN_REF}
EOF
log "neuchain containers up (topology scaffolding; adapter is Phase 4)"
