#!/usr/bin/env bash
# Bring up NeuChain (EV) for benchmarking.
#
#   bash deploy/docker/neuchain/up.sh [profile]
#
# Steps:
#   1. check the runtime image bench/neuchain:ev exists
#   2. generate RSA keys once (crypto-init) and give all four servers one user
#      keypair, so the adapter's single signing key verifies on every server
#   3. start 4 block servers (each with a co-located epoch server) on an empty
#      state DB, as every other platform starts
#   4. apply the profile budget, emit connection.env
#
# Image provenance: bench/neuchain:ev is currently the PATCHED build from
# patched/ (see patched/README.md), not a clean upstream build. Every run
# records that in manifest.platform_version.
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
need docker
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
on_error_dump '^bench-neuchain-'

cd "$HERE" || exit 1

NEUCHAIN_REF="${NEUCHAIN_REF:-ev}"
export BENCH_NC_IMAGE="${BENCH_NC_IMAGE:-bench/neuchain:${NEUCHAIN_REF}}"
BUILD_KIND="${BENCH_NC_BUILD_KIND:-patched}"

if ! docker image inspect "$BENCH_NC_IMAGE" >/dev/null 2>&1; then
  die "image ${BENCH_NC_IMAGE} missing" \
      "copied from another machine? make images-import (scripts/images.sh import <dir>)" \
      "patched build: see deploy/docker/neuchain/patched/README.md" \
      "clean upstream build: deploy/docker/neuchain/build.sh (slow: ~1h, builds ~15 C++ deps from source)"
fi

# --- crypto ------------------------------------------------------------------
CRYPTO="${HERE}/.cache/crypto"
mkdir -p "$CRYPTO"
if [ ! -f "${CRYPTO}/server.0.private.user.key" ]; then
  log "generating NeuChain RSA keys (crypto-init)"
  BENCH_UID="$(id -u)" BENCH_GID="$(id -g)" docker compose --profile init run --rm crypto-init >/dev/null \
    || die "crypto-init failed"
  docker compose --profile init rm -fsv crypto-init >/dev/null 2>&1 || true
  [ -f "${CRYPTO}/server.0.private.user.key" ] || die "crypto-init wrote no keys to ${CRYPTO}"
  # Each server verifies a UserRequest against its own server.N user key; the
  # native client signs per target server. One shared pair lets the adapter sign
  # once and round-robin, with the same per-tx verify cost on every server.
  for n in 1 2 3; do
    cp "${CRYPTO}/server.0.public.user.key"  "${CRYPTO}/server.${n}.public.user.key"
    cp "${CRYPTO}/server.0.private.user.key" "${CRYPTO}/server.${n}.private.user.key"
  done
fi

# --- network -----------------------------------------------------------------
drop_caches
docker compose up -d block-server-0 block-server-1 block-server-2 block-server-3 \
  || { compose_dump 60; die "docker compose up failed for neuchain"; }
WAIT_FOR_ON_TIMEOUT=compose_dump
for n in 0 1 2 3; do
  wait_for "block server ${n} query port :70${n}3" 120 port_open 127.0.0.1 "70${n}3" \
    || die "neuchain block server ${n} never opened :70${n}3" "compose status and logs are above"
  wait_for "block server ${n} submit port :50${n}1" 60 port_open 127.0.0.1 "50${n}1" \
    || die "neuchain block server ${n} never opened :50${n}1"
done
unset WAIT_FOR_ON_TIMEOUT
# TCP accept is not a ZMTP handshake. The last local-32gb campaign reset the
# adapter's greeting ~2s after up because the SUB socket was not yet listening
# in-process. Give the C++ servers a moment before emitting connection.env.
log "waiting 5s for NeuChain ZMQ sockets to accept handshakes"
sleep 5
RES_ENV="$(apply_budget neuchain '^bench-neuchain-block-server-')"

cat > "${HERE}/connection.env" <<EOF
# generated by deploy/docker/neuchain/up.sh  ($(date -u +%FT%TZ))
# NeuChain block servers SUB on :5001 (submit) and REP on :7003 (query), host
# ports 5001+10n / 7003+10n as in docker-compose.yml.
BENCH_ADAPTER_BLOCK_SERVERS=localhost:5001,localhost:5011,localhost:5021,localhost:5031
BENCH_ADAPTER_QUERY_ENDPOINT=localhost:7003
BENCH_ADAPTER_USER_PRIV_KEY_PATH=${CRYPTO}/server.0.private.user.key
BENCH_ADAPTER_USER_PUB_KEY_PATH=${CRYPTO}/server.0.public.user.key
BENCH_ADAPTER_TABLE_NAME=ycsb
BENCH_PLATFORM_VERSION=neuchain-${NEUCHAIN_REF}-${BUILD_KIND}
# State DB this network actually came up on; the harness records it as
# manifest.state_db next to the requested value (fairness lever).
BENCH_ACTUAL_STATE_DB=leveldb
${RES_ENV}
EOF
log "neuchain up: 4 block servers + 4 co-located epoch servers (image ${BENCH_NC_IMAGE}, ${BUILD_KIND} build)"
